"""Simulation scenarios — predefined sensor configurations for demonstration."""

SCENARIOS = {
    "normal": {
        "name": "Normal Operation",
        "description": "Normal splice with no defects — baseline behavior",
        "steps": [
            {"step": 1, "vision": 0.0, "thermal": 0.0, "mechanical": 0.0, "conductive": False},
            {"step": 2, "vision": 0.05, "thermal": 0.03, "mechanical": 0.02, "conductive": False},
            {"step": 3, "vision": 0.02, "thermal": 0.01, "mechanical": 0.04, "conductive": False},
            {"step": 4, "vision": 0.03, "thermal": 0.02, "mechanical": 0.01, "conductive": False},
            {"step": 5, "vision": 0.01, "thermal": 0.04, "mechanical": 0.03, "conductive": False},
        ],
        "duration_steps": 5,
    },
    "visual_anomaly": {
        "name": "Visual Anomaly",
        "description": "Visual defect detected by camera only",
        "steps": [
            {"step": 1, "vision": 0.0, "thermal": 0.0, "mechanical": 0.0, "conductive": False},
            {"step": 2, "vision": 0.3, "thermal": 0.05, "mechanical": 0.02, "conductive": False},
            {"step": 3, "vision": 0.6, "thermal": 0.08, "mechanical": 0.05, "conductive": False},
            {"step": 4, "vision": 0.75, "thermal": 0.1, "mechanical": 0.05, "conductive": False},
            {"step": 5, "vision": 0.8, "thermal": 0.1, "mechanical": 0.08, "conductive": False},
        ],
        "duration_steps": 5,
    },
    "thermal_anomaly": {
        "name": "Thermal Anomaly",
        "description": "Thermal anomaly — elevated temperature at splice",
        "steps": [
            {"step": 1, "vision": 0.0, "thermal": 0.0, "mechanical": 0.0, "conductive": False},
            {"step": 2, "vision": 0.05, "thermal": 0.3, "mechanical": 0.05, "conductive": False},
            {"step": 3, "vision": 0.08, "thermal": 0.55, "mechanical": 0.08, "conductive": False},
            {"step": 4, "vision": 0.1, "thermal": 0.75, "mechanical": 0.1, "conductive": False},
            {"step": 5, "vision": 0.12, "thermal": 0.85, "mechanical": 0.12, "conductive": False},
        ],
        "duration_steps": 5,
    },
    "conductive_break": {
        "name": "Conductive Break",
        "description": "Conductive loop break event",
        "steps": [
            {"step": 1, "vision": 0.0, "thermal": 0.0, "mechanical": 0.0, "conductive": False},
            {"step": 2, "vision": 0.05, "thermal": 0.05, "mechanical": 0.1, "conductive": False},
            {"step": 3, "vision": 0.1, "thermal": 0.1, "mechanical": 0.2, "conductive": True},
            {"step": 4, "vision": 0.15, "thermal": 0.12, "mechanical": 0.25, "conductive": True},
        ],
        "duration_steps": 4,
    },
    "mechanical_anomaly": {
        "name": "Mechanical Anomaly",
        "description": "Abnormal vibration pattern detected",
        "steps": [
            {"step": 1, "vision": 0.0, "thermal": 0.0, "mechanical": 0.0, "conductive": False},
            {"step": 2, "vision": 0.05, "thermal": 0.05, "mechanical": 0.35, "conductive": False},
            {"step": 3, "vision": 0.08, "thermal": 0.08, "mechanical": 0.6, "conductive": False},
            {"step": 4, "vision": 0.1, "thermal": 0.1, "mechanical": 0.8, "conductive": False},
            {"step": 5, "vision": 0.12, "thermal": 0.15, "mechanical": 0.85, "conductive": False},
        ],
        "duration_steps": 5,
    },
    "multi_sensor": {
        "name": "Multi-Sensor Defect",
        "description": "Multiple sensors detect anomalies simultaneously",
        "steps": [
            {"step": 1, "vision": 0.0, "thermal": 0.0, "mechanical": 0.0, "conductive": False},
            {"step": 2, "vision": 0.4, "thermal": 0.35, "mechanical": 0.3, "conductive": False},
            {"step": 3, "vision": 0.7, "thermal": 0.65, "mechanical": 0.6, "conductive": False},
            {"step": 4, "vision": 0.85, "thermal": 0.8, "mechanical": 0.75, "conductive": True},
        ],
        "duration_steps": 4,
    },
    "progressive_degradation": {
        "name": "Progressive Degradation",
        "description": "Gradually worsening splice condition over multiple inspections",
        "steps": [
            {"step": 1, "vision": 0.0, "thermal": 0.0, "mechanical": 0.0, "conductive": False},
            {"step": 2, "vision": 0.1, "thermal": 0.08, "mechanical": 0.05, "conductive": False},
            {"step": 3, "vision": 0.25, "thermal": 0.2, "mechanical": 0.15, "conductive": False},
            {"step": 4, "vision": 0.4, "thermal": 0.35, "mechanical": 0.3, "conductive": False},
            {"step": 5, "vision": 0.55, "thermal": 0.5, "mechanical": 0.45, "conductive": False},
            {"step": 6, "vision": 0.7, "thermal": 0.65, "mechanical": 0.6, "conductive": False},
            {"step": 7, "vision": 0.8, "thermal": 0.75, "mechanical": 0.7, "conductive": False},
            {"step": 8, "vision": 0.9, "thermal": 0.85, "mechanical": 0.8, "conductive": True},
        ],
        "duration_steps": 8,
    },
    "high_risk": {
        "name": "High-Risk Splice",
        "description": "Severe multi-sensor defect leading to critical risk",
        "steps": [
            {"step": 1, "vision": 0.0, "thermal": 0.0, "mechanical": 0.0, "conductive": False},
            {"step": 2, "vision": 0.5, "thermal": 0.45, "mechanical": 0.4, "conductive": False},
            {"step": 3, "vision": 0.8, "thermal": 0.75, "mechanical": 0.7, "conductive": True},
            {"step": 4, "vision": 0.95, "thermal": 0.9, "mechanical": 0.88, "conductive": True},
        ],
        "duration_steps": 4,
    },
    "resolved": {
        "name": "Resolved Defect",
        "description": "Defect that improves and resolves over time",
        "steps": [
            {"step": 1, "vision": 0.0, "thermal": 0.0, "mechanical": 0.0, "conductive": False},
            {"step": 2, "vision": 0.6, "thermal": 0.55, "mechanical": 0.5, "conductive": False},
            {"step": 3, "vision": 0.7, "thermal": 0.6, "mechanical": 0.55, "conductive": False},
            {"step": 4, "vision": 0.5, "thermal": 0.4, "mechanical": 0.35, "conductive": False},
            {"step": 5, "vision": 0.3, "thermal": 0.2, "mechanical": 0.15, "conductive": False},
            {"step": 6, "vision": 0.1, "thermal": 0.08, "mechanical": 0.05, "conductive": False},
            {"step": 7, "vision": 0.02, "thermal": 0.03, "mechanical": 0.02, "conductive": False},
        ],
        "duration_steps": 7,
    },
    "demo": {
        "name": "Full Demo Sequence",
        "description": "Complete demonstration: normal -> detect -> corroborate -> degrade -> high risk -> alert",
        "steps": [
            {"step": 1, "vision": 0.0, "thermal": 0.0, "mechanical": 0.0, "conductive": False, "label": "Normal operation"},
            {"step": 2, "vision": 0.05, "thermal": 0.03, "mechanical": 0.02, "conductive": False, "label": "Splice detected, normal"},
            {"step": 3, "vision": 0.35, "thermal": 0.1, "mechanical": 0.05, "conductive": False, "label": "Visual anomaly appears"},
            {"step": 4, "vision": 0.4, "thermal": 0.4, "mechanical": 0.1, "conductive": False, "label": "Thermal anomaly develops"},
            {"step": 5, "vision": 0.45, "thermal": 0.45, "mechanical": 0.45, "conductive": False, "label": "Mechanical anomaly joins"},
            {"step": 6, "vision": 0.6, "thermal": 0.55, "mechanical": 0.5, "conductive": False, "label": "Multi-sensor corroboration"},
            {"step": 7, "vision": 0.65, "thermal": 0.6, "mechanical": 0.55, "conductive": False, "label": "Temporal validation — persistent"},
            {"step": 8, "vision": 0.7, "thermal": 0.65, "mechanical": 0.6, "conductive": False, "label": "Condition degrading"},
            {"step": 9, "vision": 0.75, "thermal": 0.7, "mechanical": 0.65, "conductive": False, "label": "Risk increasing"},
            {"step": 10, "vision": 0.8, "thermal": 0.75, "mechanical": 0.7, "conductive": True, "label": "Conductive break — high risk"},
            {"step": 11, "vision": 0.85, "thermal": 0.8, "mechanical": 0.75, "conductive": True, "label": "Belt coordinate localized"},
            {"step": 12, "vision": 0.9, "thermal": 0.85, "mechanical": 0.8, "conductive": True, "label": "High priority alert generated"},
            {"step": 13, "vision": 0.92, "thermal": 0.88, "mechanical": 0.85, "conductive": True, "label": "Maintenance action recommended"},
        ],
        "duration_steps": 13,
    },
}
