import { useMemo, useState } from 'react';
import { AlertTriangle, BookOpenCheck, CheckCircle2, ClipboardCheck, Gauge, MoveHorizontal, Search, ShieldCheck, Thermometer, Wrench } from 'lucide-react';
import { demoAlerts, demoSplices } from '../data/demoData';
import MaintenanceAssistant from '../components/MaintenanceAssistant';

type FaultKey = 'critical' | 'high' | 'watch' | 'nominal';

const faultPlans: Record<FaultKey, { title: string; subtitle: string; tone: string; icon: typeof AlertTriangle; evidence: string[]; immediate: string[]; inspect: string[]; handover: string }> = {
  critical: { title: 'Critical splice separation', subtitle: 'Multi-sensor corroboration requires immediate controlled response', tone: 'border-rose-300 bg-rose-50 text-rose-800', icon: AlertTriangle, evidence: ['Vision: 91% separation confidence', 'Thermal: localized +12.6°C rise', 'DIVE: 14 correlated observations', 'ATCE: rapid degradation trend'], immediate: ['Keep people clear and notify the control room and supervisor.', 'Follow the site shutdown / emergency procedure; do not restart or bypass protection.', 'Preserve the alarm time, splice location and inspection evidence.'], inspect: ['After approved isolation, inspect cover separation, exposed cords and adjacent belt condition.', 'Capture dimensions and images before cleaning or handling the splice.', 'A qualified belt specialist decides repair method and release criteria.'], handover: 'BELT-03 · Splice-202 · 180 m · critical separation · restart prohibited pending authorized release.' },
  high: { title: 'High-priority mechanical / edge defect', subtitle: 'Expedite assessment before continued exposure increases the defect', tone: 'border-orange-300 bg-orange-50 text-orange-800', icon: Gauge, evidence: ['Vision: edge crack growth pattern', 'Mechanical: vibration RMS elevated', 'Risk model: 74% intervention priority', 'DIVE: persistent multi-window evidence'], immediate: ['Coordinate a planned inspection window with operations.', 'Do not adjust rollers or reach into a moving conveyor.', 'Record belt load, speed and exact position with the finding.'], inspect: ['After approved isolation, inspect edges, idlers, buildup and the transfer point.', 'Compare images and measurement against the prior inspection.', 'Escalate any exposed cords, expanding crack or abnormal heat.'], handover: 'High-priority inspection requested; operations coordination and qualified review required.' },
  watch: { title: 'Watch condition', subtitle: 'Trend is above baseline and needs a planned inspection response', tone: 'border-amber-300 bg-amber-50 text-amber-800', icon: Thermometer, evidence: ['Thermal / visual value exceeds baseline', 'Risk below immediate response threshold', 'Trend needs confirmation in next inspection window', 'No safety interlock fault reported'], immediate: ['Log the finding with position, time and operating conditions.', 'Schedule the next approved inspection; keep normal safety controls active.', 'Escalate sooner if severity, temperature or vibration rises.'], inspect: ['Review scraper condition, tracking, material buildup and splice cover condition.', 'Capture a repeat image and compare against the original evidence.', 'Check whether the condition changes with load or belt speed.'], handover: 'Watch condition logged; reassess during the next planned inspection interval.' },
  nominal: { title: 'Nominal condition', subtitle: 'No active fault is attached to this splice', tone: 'border-emerald-300 bg-emerald-50 text-emerald-800', icon: CheckCircle2, evidence: ['Latest inspection within normal band', 'No active corroborated anomaly', 'Monitoring cadence remains active', 'Safety interlocks nominal'], immediate: ['Keep routine inspections and housekeeping on schedule.', 'Report any visual change, tracking drift or unusual sound.', 'Use normal permit and isolation controls for planned work.'], inspect: ['During routine inspection, verify cover, edges, idlers and material buildup.', 'Record condition consistently to maintain the trend baseline.', 'Use approved procedures for any planned adjustment or repair.'], handover: 'Nominal splice; routine condition-monitoring schedule continues.' },
};

function severityFor(splice: any): FaultKey { if (splice.severity >= 0.85) return 'critical'; if (splice.severity >= 0.55) return 'high'; if (splice.severity >= 0.2) return 'watch'; return 'nominal'; }

export default function MaintenanceCenter() {
  const [selectedId, setSelectedId] = useState(11);
  const selected = demoSplices.find(item => item.id === selectedId) || demoSplices[0]; const fault = severityFor(selected); const plan = faultPlans[fault]; const Icon = plan.icon;
  const relatedAlerts = useMemo(() => demoAlerts.filter(alert => alert.splice_id === selected.id), [selected.id]);
  return <div className="space-y-4">
    <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-3"><div className="rounded-xl bg-blue-50 p-2.5 text-blue-700"><Wrench size={24}/></div><div><div className="text-[10px] font-mono font-semibold uppercase tracking-[.16em] text-blue-600">Maintenance decision workspace</div><h2 className="mt-1 text-xl font-bold text-slate-800">Guided Belt & Splice Maintenance</h2><p className="mt-1 text-sm text-slate-500">Select a monitored splice to review its condition, supporting evidence and safe work-prep approach.</p></div></div><div className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-right"><div className="text-[10px] uppercase tracking-wider text-slate-400">Selected asset</div><div className="font-mono text-sm font-semibold text-slate-700">{selected.belt_id} · {selected.name}</div></div></div></div>

    <div className="grid grid-cols-12 gap-4">
      <aside className="col-span-12 xl:col-span-3 rounded-xl border border-slate-200 bg-white p-3 shadow-sm"><div className="mb-3 flex items-center justify-between"><div><h3 className="text-sm font-bold text-slate-800">Asset selector</h3><p className="text-[10px] text-slate-500">Choose a splice to load its guidance</p></div><Search size={16} className="text-slate-400"/></div><div className="max-h-[590px] space-y-1.5 overflow-y-auto pr-1">{demoSplices.map(splice => { const state = severityFor(splice); return <button key={splice.id} onClick={() => setSelectedId(splice.id)} className={`w-full rounded-lg border p-3 text-left transition hover:border-blue-300 ${selected.id === splice.id ? 'border-blue-500 bg-blue-50 ring-1 ring-blue-300' : 'border-slate-200 bg-white'}`}><div className="flex items-center justify-between"><span className="text-xs font-bold text-slate-800">{splice.name}</span><span className={`rounded-full px-2 py-0.5 text-[9px] font-bold ${state === 'critical' ? 'bg-rose-100 text-rose-700' : state === 'high' ? 'bg-orange-100 text-orange-700' : state === 'watch' ? 'bg-amber-100 text-amber-700' : 'bg-emerald-100 text-emerald-700'}`}>{splice.condition}</span></div><div className="mt-1 font-mono text-[10px] text-slate-500">{splice.belt_id} · {splice.position} m · risk {Math.round(splice.severity * 100)}%</div></button>; })}</div></aside>

      <main className="col-span-12 xl:col-span-6 space-y-4"><section className={`rounded-xl border p-4 shadow-sm ${plan.tone}`}><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className="rounded-lg bg-white/70 p-2"><Icon size={21}/></div><div><div className="text-[10px] font-mono font-bold uppercase tracking-[.14em]">Current condition · {selected.condition}</div><h3 className="mt-1 text-lg font-bold">{plan.title}</h3><p className="mt-1 text-sm opacity-80">{plan.subtitle}</p></div></div><span className="rounded bg-white/70 px-2 py-1 font-mono text-[10px]">{selected.belt_id} / {selected.position}m</span></div></section>
        <section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center gap-2"><BookOpenCheck size={17} className="text-violet-600"/><h3 className="text-sm font-bold text-slate-800">Evidence linked to this selection</h3></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-2">{plan.evidence.map(item => <div key={item} className="rounded-lg border border-slate-100 bg-slate-50 px-3 py-2 text-xs text-slate-600"><span className="mr-2 inline-block h-1.5 w-1.5 rounded-full bg-violet-500"/>{item}</div>)}</div>{relatedAlerts.length > 0 && <div className="mt-3 rounded-lg border border-rose-100 bg-rose-50 p-3"><div className="text-[10px] font-bold uppercase tracking-wider text-rose-700">Linked alerts</div>{relatedAlerts.map(alert => <div key={alert.id} className="mt-1.5 flex justify-between gap-3 text-xs"><span className="font-medium text-rose-800">#{alert.id} · {alert.defect_type.replace(/_/g, ' ')}</span><span className="font-mono text-rose-700">{Math.round(alert.risk_score * 100)}%</span></div>)}</div>}</section>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center gap-2"><ShieldCheck size={17} className="text-emerald-600"/><h3 className="text-sm font-bold text-slate-800">Approach now</h3></div><ol className="space-y-3">{plan.immediate.map((item, index) => <li key={item} className="flex gap-2 text-xs leading-5 text-slate-600"><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-emerald-50 text-[10px] font-bold text-emerald-700">{index + 1}</span>{item}</li>)}</ol></section><section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-3 flex items-center gap-2"><ClipboardCheck size={17} className="text-blue-600"/><h3 className="text-sm font-bold text-slate-800">Inspection prep</h3></div><ol className="space-y-3">{plan.inspect.map((item, index) => <li key={item} className="flex gap-2 text-xs leading-5 text-slate-600"><span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-blue-50 text-[10px] font-bold text-blue-700">{index + 1}</span>{item}</li>)}</ol></section></div>
        <MaintenanceAssistant embedded isDark contextLabel={`${selected.belt_id} · ${selected.name} · ${selected.position} m · ${plan.title}`} /></main>

      <aside className="col-span-12 xl:col-span-3 space-y-4"><section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2"><MoveHorizontal size={17} className="text-blue-600"/><h3 className="text-sm font-bold text-slate-800">Condition path</h3></div><div className="mt-5 space-y-0">{['NORMAL', 'WATCH', 'HIGH PRIORITY', 'CRITICAL'].map((state, index) => <div key={state}><div className={`rounded-lg border p-2.5 text-xs ${state === (fault === 'watch' ? 'WATCH' : fault === 'high' ? 'HIGH PRIORITY' : fault === 'critical' ? 'CRITICAL' : 'NORMAL') ? plan.tone : 'border-slate-200 bg-slate-50 text-slate-400'}`}><div className="font-bold">{state}</div><div className="mt-0.5 text-[10px] opacity-80">{['Routine monitor', 'Plan inspection', 'Expedite review', 'Controlled response'][index]}</div></div>{index < 3 && <div className="ml-5 h-4 border-l-2 border-dashed border-slate-300"/>}</div>)}</div></section><section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2"><ClipboardCheck size={17} className="text-slate-600"/><h3 className="text-sm font-bold text-slate-800">Handover note</h3></div><p className="mt-3 rounded-lg bg-slate-50 p-3 text-xs leading-5 text-slate-600">{plan.handover}</p><button onClick={() => navigator.clipboard?.writeText(plan.handover)} className="mt-3 flex w-full items-center justify-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 transition hover:bg-slate-50 active:scale-[.98]"><ClipboardCheck size={14}/>Copy handover note</button></section></aside>
    </div>
  </div>;
}
